#!/bin/bash

sudo apt-get install git-core

localdir="$HOME/cayuga"

if [ -d "$localdir" ]; then
    rm -rf "$localdir"
fi

cd $HOME
git clone git@github.com:kixxauth/cayuga.git

PATH="$localdir/bin:$PATH"

echo "OK - toehold is done"
