#!/bin/bash

sudo apt-get install git-core

localdir="$HOME/sak_server"

if [ -d "$localdir" ]; then
    rm -rf "$localdir"
fi

cd $HOME
git clone git@github.com:FireworksProject/sak_server.git

PATH="$localdir/bin:$PATH"

echo "OK - toehold is done"
